// 100 realistic Forestry SSW questions
const questions = [
  {"jp":"受口の角度は30度から45度が適切である。","hira":"うけぐちのかくどはさんじゅうどからよんじゅうごどがてきせつである。","en":"Proper notch angle is 30–45°.","reason":"Standard notch angle for controlled felling.","source":"gaikoku-11 p.12","answer":true},
  {"jp":"伐倒後はできるだけ速やかに安全な場所へ退避する必要がある。","hira":"ばっとうごはできるだけすみやかにあんぜんなばしょへたいひするひつようがある。","en":"Evacuate immediately after felling.","reason":"Reduce exposure to residual hazards.","source":"gaikoku-11 p.14","answer":true},
  {"jp":"つるの幅は直径の約1/10が目安である。","hira":"つるのはばはちょっけいのやくじゅうぶんのいちがめやすである。","en":"Hinge (tsuru) ≈ 1/10 of diameter.","reason":"Maintains control of fall.","source":"gaikoku-11 p.13","answer":true},
  {"jp":"立入禁止範囲は伐倒木の高さの2倍に設定する。","hira":"たちいりきんしくいきはばっとうぼくのたかさのにばいにせっていする。","en":"No-entry zone ≈ 2× tree height.","reason":"Common safety margin.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"退避位置は伐倒木から最低3メートルが必要である。","hira":"たいひいちはばっとうぼくからさいていさんめーとるがひつようである。","en":"Retreat point ≥ 3 m.","reason":"Keeps clear of hazards.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"受口の角度は60度が適当である。","hira":"うけぐちのかくどはろくじゅうどがてきとうである。","en":"A 60° notch angle is appropriate.","reason":"False — too wide; use 30–45°.","source":"gaikoku-11 p.12","answer":false},
  {"jp":"伐倒後は30分以内に退避すれば良い。","hira":"ばっとうごはさんじゅっぷんいないにたいひすればよい。","en":"Evacuating within 30 minutes is fine.","reason":"False — evacuate ASAP.","source":"gaikoku-11 p.14","answer":false},
  {"jp":"チェーンソーのチェーンブレーキは使用前に点検する。","hira":"ちぇーんそーのちぇーんぶれーきはしようまえにてんけんする。","en":"Check chain brake before use.","reason":"Ensures emergency stop.","source":"gaikoku-11 p.20","answer":true},
  {"jp":"チェーンブレーキの点検は省略して良い。","hira":"ちぇーんぶれーきのてんけんはしょうりゃくしてよい。","en":"You can skip chain-brake check.","reason":"False — increases risk.","source":"gaikoku-11 p.20","answer":false},
  {"jp":"刈払機の刃は使用前に損傷がないか点検する。","hira":"かりはらいきのははしようまえにそんしょうがないかてんけんする。","en":"Inspect brushcutter blade for damage.","reason":"Prevent fragmentation injuries.","source":"ringyo p.7","answer":true},
  {"jp":"刈払機の燃料補給はエンジン停止後に行う。","hira":"かりはらいきのねんりょうほきゅうはえんじんていしごにおこなう。","en":"Refuel after engine stop.","reason":"Lower fire risk.","source":"ringyo p.8","answer":true},
  {"jp":"作業前に気象を確認する必要はない。","hira":"さぎょうまえにきしょうをかくにんするひつようはない。","en":"No need to check weather.","reason":"False — affects safety.","source":"gaikoku-11 p.14","answer":false},
  {"jp":"伐倒方向の確認は重要である。","hira":"ばっとうほうこうのかくにんはじゅうようである。","en":"Confirm felling direction.","reason":"Predictable fall path.","source":"gaikoku-11 p.12","answer":true},
  {"jp":"伐採作業は常に一人が安全である。","hira":"ばっさいさぎょうはつねにひとりがあんぜんである。","en":"Working alone is safer.","reason":"False — delays help.","source":"gaikoku-11 p.16","answer":false},
  {"jp":"現場には救急用品を用意する。","hira":"げんばにはきゅうきゅうようひんをよういする。","en":"Keep first-aid kit on site.","reason":"Immediate response.","source":"ringyo p.3","answer":true},
  {"jp":"裸苗は乾燥対策不要である。","hira":"はだかなえはかんそうたいさくふようである。","en":"Bare-root seedlings need no moisture care.","reason":"False — high drying risk.","source":"gaikoku-11 p.41","answer":false},
  {"jp":"下刈りは苗の成長を助ける。","hira":"したがりはなえのせいちょうをたすける。","en":"Undercutting helps growth.","reason":"Reduces weed competition.","source":"ringyo p.10","answer":true},
  {"jp":"枝打ちは長枝を段階的に切る。","hira":"えだうちはちょうしをだんかいてきにきる。","en":"Cut long branches in stages.","reason":"Prevents tearing.","source":"gaikoku-11 p.18","answer":true},
  {"jp":"残材は放置してよい。","hira":"ざんざいはほうちしてよい。","en":"Leave residues as-is.","reason":"False — hazards/pests.","source":"gaikoku-11 p.31","answer":false},
  {"jp":"バー先端で切断しない。","hira":"ばーせんたんできらない。","en":"Avoid bar tip cutting.","reason":"Kickback risk.","source":"gaikoku-11 p.20","answer":true},
  {"jp":"耳栓は不要である。","hira":"みみせんはふようである。","en":"Hearing protection is unnecessary.","reason":"False — high noise.","source":"gaikoku-11 p.22","answer":false},
  {"jp":"周囲の人の位置を確認する。","hira":"しゅういのひとのいちをかならずかくにんする。","en":"Check others' positions.","reason":"Prevent injuries.","source":"gaikoku-11 p.14","answer":true},
  {"jp":"立入禁止は重要ではない。","hira":"たちいりきんしはじゅうようではない。","en":"No-entry zones are unimportant.","reason":"False — critical control.","source":"gaikoku-11 p.15","answer":false},
  {"jp":"刈払機は定期的に保守する。","hira":"かりはらいきはていきてきにほしゅする。","en":"Maintain brushcutters regularly.","reason":"Safety/longevity.","source":"ringyo p.8","answer":true},
  {"jp":"損傷刃でも使用できる。","hira":"そんしょうばでもしようできる。","en":"Damaged blades are fine.","reason":"False — fragmentation risk.","source":"ringyo p.7","answer":false},
  {"jp":"退避ルートを打合せで確認する。","hira":"たいひるーとをうちあわせでかくにんする。","en":"Confirm escape routes.","reason":"Emergency readiness.","source":"gaikoku-11 p.14","answer":true},
  {"jp":"作業中の携帯電話使用は問題ない。","hira":"さぎょうちゅうのけいたいでんわしようはもんだいない。","en":"Using phone during work is fine.","reason":"False — distraction hazard.","source":"gaikoku-11 p.14","answer":false},
  {"jp":"ヘルメットとフェイスシールドは推奨される。","hira":"へるめっととふぇいすしーるどはすいしょうされる。","en":"Helmet & face shield are recommended.","reason":"Protects from debris.","source":"gaikoku-11 p.22","answer":true},
  {"jp":"追い口は受口より高く切るのが基本である。","hira":"おいぐちはうけぐちよりたかくきるのがきほんである。","en":"Back cut above the notch.","reason":"Preserves hinge.","source":"gaikoku-11 p.12","answer":true},
  {"jp":"追い口は受口より低い方が安全である。","hira":"おいぐちはうけぐちよりひくいほうがあんぜんである。","en":"Back cut lower is safer.","reason":"False — barber chair risk.","source":"gaikoku-11 p.12","answer":false},
  {"jp":"受口は狙う方向に正しく向ける。","hira":"うけぐちはねらうほうこうにただしくむける。","en":"Aim notch to fall direction.","reason":"Guides fall.","source":"gaikoku-11 p.12","answer":true},
  {"jp":"つるは完全に切断してから退避する。","hira":"つるはかんぜんにせつだんしてからたいひする。","en":"Cut hinge off before retreat.","reason":"False — hinge controls fall.","source":"gaikoku-11 p.13","answer":false},
  {"jp":"くさびで方向補助ができる。","hira":"くさびでほうこうほじょができる。","en":"Wedges help guide fall.","reason":"Prevents pinching.","source":"gaikoku-11 p.13","answer":true},
  {"jp":"強風時は高木の伐倒を避ける。","hira":"きょうふうじはこうぼくのばっとうをさける。","en":"Avoid felling tall trees in strong wind.","reason":"Unpredictable movement.","source":"gaikoku-11 p.14","answer":true},
  {"jp":"指揮者の合図なしで伐倒してよい。","hira":"しきしゃのあいずなしでばっとうしてよい。","en":"Fell without signal.","reason":"False — communication is critical.","source":"gaikoku-11 p.14","answer":false},
  {"jp":"退避方向は伐倒方向から45度後方が基本である。","hira":"たいひほうこうはばっとうほうこうからよんじゅうごどこうほうがきほんである。","en":"Retreat ~45° back.","reason":"Avoids butt kick.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"切株は高く残すほど安全である。","hira":"きりかぶはたかくのこすほどあんぜんである。","en":"Higher stump is safer.","reason":"False — not necessarily safer.","source":"gaikoku-11 p.12","answer":false},
  {"jp":"相互監視（バディ）で作業する。","hira":"そうごかんし（ばでぃ）でさぎょうする。","en":"Use buddy system.","reason":"Faster issue detection.","source":"ringyo p.3","answer":true},
  {"jp":"チェーン張りを始動前に確認する。","hira":"ちぇーんはりをしどうまえにかくにんする。","en":"Check chain tension before start.","reason":"Derail/overheat control.","source":"gaikoku-11 p.20","answer":true},
  {"jp":"バーオイルは不要で性能に影響しない。","hira":"ばーおいるはふようでせいのうにえいきょうしない。","en":"Bar oil not needed.","reason":"False — lubrication is essential.","source":"gaikoku-11 p.20","answer":false},
  {"jp":"キックバックゾーン（先端上部）に注意する。","hira":"きっくばっくぞーん（せんたんじょうぶ）にちゅういする。","en":"Beware kickback zone.","reason":"Primary cause of kickback.","source":"gaikoku-11 p.20","answer":true},
  {"jp":"不安定な足場でも同じ手順で良い。","hira":"ふあんていなあしばでもおなじてじゅんでよい。","en":"Same steps on unstable footing.","reason":"False — stabilize or postpone.","source":"gaikoku-11 p.14","answer":false},
  {"jp":"斜面では上側から近づくのが安全である。","hira":"しゃめんではうえがわからちかづくのがあんぜんである。","en":"Approach from uphill side.","reason":"Reduces roll risk.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"かかり木は機械等で処理する。","hira":"かかりぎはきかいとうでしょりする。","en":"Handle hung-up trees with equipment.","reason":"Avoid climbing hazards.","source":"gaikoku-11 p.16","answer":true},
  {"jp":"かかり木は登って外してよい。","hira":"かかりぎはのぼってはずしてよい。","en":"Climb to free a hung-up tree.","reason":"False — extremely dangerous.","source":"gaikoku-11 p.16","answer":false},
  {"jp":"受口方向線はコンパス等で確認する。","hira":"うけぐちほうこうせんはこんぱすなどでかくにんする。","en":"Use compass/markers.","reason":"Increases accuracy.","source":"gaikoku-11 p.12","answer":true},
  {"jp":"退避路は2本以上確保する。","hira":"たいひろはにほんいじょうかくほする。","en":"Secure at least two escape paths.","reason":"Redundancy.","source":"gaikoku-11 p.14","answer":true},
  {"jp":"退避路は伐倒方向へまっすぐが最適である。","hira":"たいひろはばっとうほうこうへまっすぐがさいてきである。","en":"Straight towards fall is best.","reason":"False — go diagonally back.","source":"gaikoku-11 p.15","answer":false},
  {"jp":"飲酒は厳禁である。","hira":"いんしゅはげんきんである。","en":"No alcohol during work.","reason":"Impairment risk.","source":"ringyo p.2","answer":true},
  {"jp":"チャップスは有効である。","hira":"ちゃっぷすはゆうこうである。","en":"Chainsaw chaps are effective.","reason":"Fibers jam the chain.","source":"gaikoku-11 p.22","answer":true},
  {"jp":"目立て角の点検を行う。","hira":"めたてかくのてんけんをおこなう。","en":"Check sharpening angle.","reason":"Cutting efficiency.","source":"gaikoku-11 p.21","answer":true},
  {"jp":"デプスゲージは調整不要である。","hira":"でぷすげーじはちょうせいふようである。","en":"Depth gauge never needs adjust.","reason":"False — affects bite.","source":"gaikoku-11 p.21","answer":false},
  {"jp":"換気の良い場所で補給する。","hira":"かんきのよいばしょでほきゅうする。","en":"Refuel in ventilated area.","reason":"Vapor/fire safety.","source":"ringyo p.8","answer":true},
  {"jp":"熱いエンジンのまま補給してよい。","hira":"あついえんじんのままほきゅうしてよい。","en":"Refuel with hot engine.","reason":"False — fire risk.","source":"ringyo p.8","answer":false},
  {"jp":"先端ガードやスパイクを適切に使う。","hira":"せんたんがーどやすぱいくをてきせつにつかう。","en":"Use tip guard/spikes properly.","reason":"Control and leverage.","source":"gaikoku-11 p.20","answer":true},
  {"jp":"障害物がある場合は除去や方向変更を検討する。","hira":"しょうがいぶつがあるばあいはじょきょやほうこうへんこうをけんとうする。","en":"Remove obstacles or change direction.","reason":"Avoid strikes/hang-ups.","source":"gaikoku-11 p.12","answer":true},
  {"jp":"ロープで引くときは結び目とアンカーを点検する。","hira":"ろーぷでひくときはむすびめとあんかーをてんけんする。","en":"Check knots and anchors.","reason":"Prevent failure.","source":"gaikoku-11 p.16","answer":true},
  {"jp":"地形勾配は考慮しなくてよい。","hira":"ちけいこうばいはこうりょしなくてよい。","en":"Ignore slope for fall direction.","reason":"False — affects roll/slide.","source":"gaikoku-11 p.12","answer":false},
  {"jp":"枝払いは安定した姿勢で行う。","hira":"えだばらいはあんていしたしせいでおこなう。","en":"Limb from stable footing.","reason":"Avoid secondary accidents.","source":"gaikoku-11 p.18","answer":true},
  {"jp":"キックバックゾーンを積極的に使う。","hira":"きっくばっくぞーんをせっきょくてきにつかう。","en":"Use kickback zone actively.","reason":"False — avoid tip contact.","source":"gaikoku-11 p.20","answer":false},
  {"jp":"玉切りは張力と圧縮を見極めてから切る。","hira":"たまぎりはちょうりょくとあっしゅくをみきわめてからきる。","en":"Assess tension/compression for bucking.","reason":"Avoid pinching/snap.","source":"gaikoku-11 p.19","answer":true},
  {"jp":"玉切りは常に一気に上から切るのが正しい。","hira":"たまぎりはつねにいっきにうえからきるのがただしい。","en":"Always one-pass top cut.","reason":"False — adapt top/bottom.","source":"gaikoku-11 p.19","answer":false},
  {"jp":"チェーンソーは両手でしっかり握る。","hira":"ちぇーんそーはりょうてでしっかりにぎる。","en":"Grip with both hands.","reason":"Control and safety.","source":"gaikoku-11 p.20","answer":true},
  {"jp":"片手切りは効率的なので推奨される。","hira":"かたてぎりはこうりつてきなのですいしょうされる。","en":"One-hand cutting is recommended.","reason":"False — very dangerous.","source":"gaikoku-11 p.20","answer":false},
  {"jp":"チョークやスロットルロックを理解する。","hira":"ちょーくやすろっとるろっくをりかいする。","en":"Understand choke/throttle lock.","reason":"Proper starting/safety.","source":"ringyo p.8","answer":true},
  {"jp":"保護めがねやフェイスシールドで木屑から目を守る。","hira":"ほごめがねやふぇいすしーるどできずからめをまもる。","en":"Eye/face PPE protects from chips.","reason":"Reduce eye injuries.","source":"gaikoku-11 p.22","answer":true},
  {"jp":"鋸目詰まりは大量の油をかけて解決する。","hira":"のこめづまりはたいりょうのおゆをかけてかいけつする。","en":"Fix chip clog by pouring oil.","reason":"False — clear chips/sharpen.","source":"gaikoku-11 p.21","answer":false},
  {"jp":"作業範囲は標識やテープで明示する。","hira":"さぎょうはんいはひょうしきやてーぷでめいじする。","en":"Mark work zones clearly.","reason":"Keep others out.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"人が入っても作業を続ける。","hira":"ひとがはいってもさぎょうをつづける。","en":"Continue when someone enters zone.","reason":"False — stop and clear.","source":"gaikoku-11 p.15","answer":false},
  {"jp":"移動時はスロットルを握らない。","hira":"いどうじはすろっとるをにぎらない。","en":"Do not hold throttle when moving.","reason":"Avoid accidental accel.","source":"ringyo p.8","answer":true},
  {"jp":"ブレーキ解除のまま移動してよい。","hira":"ぶれーきかいじょのままいどうしてよい。","en":"Move with brake off.","reason":"False — engage brake.","source":"ringyo p.8","answer":false},
  {"jp":"燃料は適切な容器でラベル保管する。","hira":"ねんりょうはてきせつなようきでらべるほかんする。","en":"Store fuel in labeled containers.","reason":"Avoid mix-up hazards.","source":"ringyo p.8","answer":true},
  {"jp":"防振手袋は長時間作業で有効である。","hira":"ぼうしんてぶくろはちょうじかんさぎょうでゆうこうである。","en":"Anti-vibration gloves help.","reason":"Reduce HAVS risk.","source":"gaikoku-11 p.22","answer":true},
  {"jp":"イヤマフは使用しない方がよい。","hira":"いやまふはしようしないほうがよい。","en":"Don't use earmuffs.","reason":"False — use properly.","source":"gaikoku-11 p.22","answer":false},
  {"jp":"スナッグ（枯損木）は危険である。","hira":"すなっぐ（こそんぼく）はきけんである。","en":"Dead snags are dangerous.","reason":"Unstable falls.","source":"gaikoku-11 p.16","answer":true},
  {"jp":"伐倒方向の下草は事前に整理する。","hira":"ばっとうほうこうのしたくさはじぜんにせいりする。","en":"Clear understory along fall line.","reason":"Better movement/vision.","source":"gaikoku-11 p.14","answer":true},
  {"jp":"受口の深さは直径の1/2以上が良い。","hira":"うけぐちのふかさはちょっけいのはんいじょうがよい。","en":"Notch depth > 1/2 diameter.","reason":"False — typical 1/4–1/3 D.","source":"gaikoku-11 p.12","answer":false},
  {"jp":"チェーンの進行方向を確認する。","hira":"ちぇーんのしんこうほうこうをかくにんする。","en":"Check chain direction.","reason":"Backwards chain won't cut.","source":"gaikoku-11 p.21","answer":true},
  {"jp":"計画書やリスク評価を事前に作成する。","hira":"けいかくしょやりすくひょうかをじぜんにさくせいする。","en":"Prepare plan and risk assessment.","reason":"Organize controls.","source":"ringyo p.2","answer":true},
  {"jp":"無線や合図で連絡を取る。","hira":"むせんやあいずでれんらくをとる。","en":"Use radios/hand signals.","reason":"Maintain comms.","source":"ringyo p.3","answer":true},
  {"jp":"雨天時は滑りにくいので注意不要である。","hira":"うてんじはすべりにくいのでちゅういふようである。","en":"Wet is less slippery.","reason":"False — slip risk rises.","source":"gaikoku-11 p.14","answer":false},
  {"jp":"長材の搬出では挟まれ・転倒に注意する。","hira":"ちょうざいのはんしゅつでははさまれ・てんとうにちゅういする。","en":"Beware pinch/fall in long log handling.","reason":"Common injuries.","source":"ringyo p.11","answer":true},
  {"jp":"伐根は周囲を掘って回転させて抜根することがある。","hira":"ばっこんはしゅういをほってかいてんさせてばっこんすることがある。","en":"Excavate and rotate stump extraction.","reason":"Site-dependent method.","source":"gaikoku-11 p.34","answer":true},
  {"jp":"間伐の目的は材積を減らすことだけである。","hira":"かんばつのもくてきはざいせきをへらすことだけである。","en":"Thinning only reduces volume.","reason":"False — improve growth/quality.","source":"gaikoku-11 p.33","answer":false},
  {"jp":"間伐後は冠に十分な光が入るのが望ましい。","hira":"かんばつごはかんにじゅうぶんなひかりがはいるのがのぞましい。","en":"After thinning allow more light.","reason":"Stimulates residual growth.","source":"gaikoku-11 p.33","answer":true},
  {"jp":"植栽後に土を踏み固めすぎない。","hira":"しょくさいごにつちをふみかためすぎない。","en":"Avoid over-compaction after planting.","reason":"Harms roots.","source":"gaikoku-11 p.41","answer":true},
  {"jp":"雑草は苗の成長を助けるので残す。","hira":"ざっそうはなえのせいちょうをたすけるのでのこす。","en":"Weeds help seedlings.","reason":"False — compete strongly.","source":"ringyo p.10","answer":false},
  {"jp":"バットキックに注意する。","hira":"ばっときっくにちゅういする。","en":"Watch for butt-kick rebound.","reason":"Can strike operator.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"受口の開き角は30度未満が安全である。","hira":"うけぐちのひらきかくはさんじゅうどみまんがあんぜんである。","en":"Opening < 30° is safest.","reason":"False — too small closes early.","source":"gaikoku-11 p.12","answer":false},
  {"jp":"追い口はつる厚みを均一に保つ。","hira":"おいぐちはつるあつみをきんいつにたもつ。","en":"Keep hinge thickness uniform.","reason":"Predictable control.","source":"gaikoku-11 p.13","answer":true},
  {"jp":"ボアカットは幹割れ防止に有効な場合がある。","hira":"ぼあかっとはみきわれぼうしにゆうこうなばあいがある。","en":"Bore cut can prevent splits.","reason":"Reduce barber chair.","source":"gaikoku-11 p.13","answer":true},
  {"jp":"ボアカットは常に危険なので禁止である。","hira":"ぼあかっとはつねにきけんなのできんしである。","en":"Bore cut always dangerous; ban.","reason":"False — trained use is valid.","source":"gaikoku-11 p.13","answer":false},
  {"jp":"刃物交換はエンジン停止・プラグ抜去後に行う。","hira":"はものこうかんはえんじんていし・ぷらぐばっきょごにおこなう。","en":"Change blades after engine off & plug removed.","reason":"Prevents accidental start.","source":"ringyo p.7","answer":true},
  {"jp":"安全靴はつま先保護と滑り止めが必要である。","hira":"あんぜんぐつはつまさきほごとすべりどめがひつようである。","en":"Safety shoes need toe cap & grip.","reason":"Crush/slip protection.","source":"gaikoku-11 p.22","answer":true},
  {"jp":"チェーンテンションは温まると緩む傾向がある。","hira":"ちぇーんてんしょんはあたたまるとゆるむけいこうがある。","en":"Chain loosens as it warms.","reason":"Thermal expansion.","source":"gaikoku-11 p.21","answer":true},
  {"jp":"電線があっても距離があれば問題ない。","hira":"でんせんがあってもきょりがあればもんだいない。","en":"Overhead lines are fine if far.","reason":"False — maintain clearance/avoid.","source":"gaikoku-11 p.12","answer":false},
  {"jp":"再開時は全員の位置確認から始める。","hira":"さいかいじはぜんいんのいちかくにんからはじめる。","en":"On resume, reconfirm positions.","reason":"Reset awareness.","source":"ringyo p.3","answer":true},
  {"jp":"運搬機周囲に2倍高さの立入禁止を設けることがある。","hira":"うんぱんきしゅういににばいたかさのたちいりきんしをもうけることがある。","en":"No-entry ≈ 2× machine height (case dependent).","reason":"Matches swing envelope.","source":"ringyo p.12","answer":true},
  {"jp":"丸太を転がすときは下側に立つのが安全である。","hira":"まるたをころがすときはしたがわにたつのがあんぜんである。","en":"Stand downhill of rolling logs.","reason":"False — stand uphill/side.","source":"ringyo p.11","answer":false},
  {"jp":"サイレンサー損傷は火災リスクを高める。","hira":"さいれんさーそんしょうはかさいりすくをたかめる。","en":"Damaged muffler raises fire risk.","reason":"Hot exhaust ignites debris.","source":"ringyo p.8","answer":true},
  {"jp":"燃料をこぼしたらすぐ始動して乾かす。","hira":"ねんりょうをこぼしたらすぐしどうしてかわかす。","en":"Start engine to dry spilled fuel.","reason":"False — clean & wait away from ignition.","source":"ringyo p.8","answer":false},
  {"jp":"枝払いは根元側から先端へ進むのが基本である。","hira":"えだばらいはねもとがわからせんたんへすすむのがきほんである。","en":"Limb from butt to tip.","reason":"Better stability.","source":"gaikoku-11 p.18","answer":true},
  {"jp":"見物人の立入を許可してもよい。","hira":"けんぶつにんのたちいりをきょかしてもよい。","en":"Allow spectators.","reason":"False — restrict access.","source":"gaikoku-11 p.15","answer":false},
  {"jp":"保管時はカバーを付け乾いた場所に置く。","hira":"ほかんじはかばーをつけてかわいたばしょにおく。","en":"Store with scabbard in dry place.","reason":"Avoid rust/injury.","source":"ringyo p.8","answer":true},
  {"jp":"油で濡れた手袋でも問題ない。","hira":"あぶらでぬれたてぶくろでももんだいない。","en":"Oily gloves are fine.","reason":"False — poor grip.","source":"ringyo p.8","answer":false},
  {"jp":"根返りに注意する。","hira":"ねがえりにちゅういする。","en":"Beware root plate movement.","reason":"Ground shift risk.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"つるの幅は直径の1/3が標準である。","hira":"つるのはばはちょっけいのさんぶんのいちがひょうじゅんである。","en":"Hinge 1/3 diameter is standard.","reason":"False — about 1/10 typical.","source":"gaikoku-11 p.13","answer":false},
  {"jp":"逃げ道確保のため下草を刈る。","hira":"にげみちかくほのためしたくさをかる。","en":"Cut brush to open escape path.","reason":"Less trip hazard.","source":"gaikoku-11 p.14","answer":true},
  {"jp":"曲がったガイドバーでも精度は落ちない。","hira":"まがったがいどばーでもせいどはおちない。","en":"Bent bar has no impact.","reason":"False — causes wandering cuts.","source":"gaikoku-11 p.21","answer":false},
  {"jp":"退避場所は伐倒方向の反対側に置く。","hira":"たいひばしょはばっとうほうこうのはんたいがわにおく。","en":"Place retreat opposite fall line.","reason":"Out of path.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"119番通報や集合場所を事前に決める。","hira":"119ばんつうほうやしゅうごうばしょをじぜんにきめる。","en":"Plan emergency call/muster point.","reason":"Faster response.","source":"ringyo p.3","answer":true},
  {"jp":"受口の方向がずれても後で押せば直る。","hira":"うけぐちのほうこうがずれてもあとでおせばなおる。","en":"Push the tree to correct mis-aim.","reason":"False — fix at setup.","source":"gaikoku-11 p.12","answer":false},
  {"jp":"デッドウッド落下の危険を確認する。","hira":"でっどうっどらっかのきけんをかくにんする。","en":"Check for dead branches overhead.","reason":"Widowmaker hazard.","source":"gaikoku-11 p.16","answer":true},
  {"jp":"耳栓は片耳だけでも同じ効果である。","hira":"みみせんはかたみみだけでもおなじこうかである。","en":"One earplug equals two.","reason":"False — fit both.","source":"gaikoku-11 p.22","answer":false},
  {"jp":"肩より高い位置での切断は避ける。","hira":"かたよりたかいいちでのせつだんはさける。","en":"Avoid above-shoulder cutting.","reason":"Loss of control.","source":"gaikoku-11 p.20","answer":true},
  {"jp":"交換後は回転方向と締付を確認する。","hira":"こうかんごはかいてんほうこうとしめつけをかくにんする。","en":"After change, verify rotation/fasteners.","reason":"Prevents failure.","source":"ringyo p.7","answer":true},
  {"jp":"長髪を束ねる必要はない。","hira":"ちょうはつをたばねるひつようはない。","en":"No need to tie long hair.","reason":"False — entanglement risk.","source":"ringyo p.3","answer":false},
  {"jp":"救助経路と集合場所を朝礼で共有する。","hira":"きゅうじょけいろとしゅうごうばしょをちょうれいできょうゆうする。","en":"Share rescue routes/muster point.","reason":"Faster response.","source":"ringyo p.3","answer":true},
  {"jp":"つるの左右幅は均一にする。","hira":"つるのさゆうはばはきんいつにする。","en":"Uniform hinge width both sides.","reason":"Balanced control.","source":"gaikoku-11 p.13","answer":true},
  {"jp":"転がり方向に立つのが効率的である。","hira":"ころがりほうこうにたつのがこうりつてきである。","en":"Stand in roll path for efficiency.","reason":"False — stand clear.","source":"gaikoku-11 p.19","answer":false},
  {"jp":"作業靴の滑り止めソールは定期交換する。","hira":"さぎょうぐつのすべりどめそーるはていきこうかんする。","en":"Replace worn soles periodically.","reason":"Maintain traction.","source":"ringyo p.22","answer":true},
  {"jp":"準備段階でチェーンブレーキを解除しておく。","hira":"じゅんびだんかいでちぇーんぶれーきをかいじょしておく。","en":"Release brake during setup.","reason":"False — keep engaged until cut.","source":"gaikoku-11 p.20","answer":false},
  {"jp":"倒れる直前まで木から目を離さない。","hira":"たおれるちょくぜんまできからめをはなさない。","en":"Keep eyes on tree until movement is controlled.","reason":"Situational awareness.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"伐倒直後は静止まで近づかない。","hira":"ばっとうちょくごはせいしまでちかづかない。","en":"Stay back until stabilized.","reason":"Avoid late shifts/limbs.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"欠けたカッターは放置してよい。","hira":"かけたかったーはほうちしてよい。","en":"Chipped cutters are fine.","reason":"False — repair/replace.","source":"gaikoku-11 p.21","answer":false},
  {"jp":"重量物は膝を使って持ち上げる。","hira":"じゅうりょうぶつはひざをつかってもちあげる。","en":"Lift with legs, not back.","reason":"Reduce injury.","source":"ringyo p.11","answer":true},
  {"jp":"丸太は肩に担いで運ぶのが最も安全である。","hira":"まるたはかたにかついではこぶのがもっともあんぜんである。","en":"Carrying logs on shoulder is safest.","reason":"False — use aids/tools.","source":"ringyo p.11","answer":false},
  {"jp":"点火スイッチ位置を周知しておく。","hira":"てんかすいっちいちをしゅうちしておく。","en":"Know on/off switch location.","reason":"Quick shutdown.","source":"ringyo p.8","answer":true},
  {"jp":"伐倒線上へ逃げるのが最短で安全である。","hira":"ばっとうせんじょうへにげるのがさいたんであんぜんである。","en":"Escape along fall line is safest.","reason":"False — retreat diagonally.","source":"gaikoku-11 p.15","answer":false},
  {"jp":"草刈り時は石跳ねに注意しガードを装着する。","hira":"くさかりじはいしはねにちゅういしがーどをそうちゃくする。","en":"Use guard; beware thrown stones.","reason":"Protect operator/bystanders.","source":"ringyo p.7","answer":true},
  {"jp":"刈払機は片手でも問題ない。","hira":"かりはらいきはかたてでももんだいない。","en":"One-hand brushcutter is fine.","reason":"False — two-handed control.","source":"ringyo p.7","answer":false},
  {"jp":"受口を予想線に正確に作る。","hira":"うけぐちをよそうせんにせいかくにつくる。","en":"Make notch precisely to aim line.","reason":"Improves accuracy.","source":"gaikoku-11 p.12","answer":true},
  {"jp":"伐倒前は合図音で周囲に警戒を促す。","hira":"ばっとうまえはあいずおんでしゅういにけいかいをうながす。","en":"Signal before felling.","reason":"Warn & clear area.","source":"ringyo p.3","answer":true},
  {"jp":"ノコ刃交換は素手がよい。","hira":"のこばこうかんはすでがよい。","en":"Change blades bare-handed.","reason":"False — cut risk; wear gloves.","source":"ringyo p.7","answer":false},
  {"jp":"チェーンのたるみは先端で約5mmを目安とする。","hira":"ちぇーんのたるみはせんたんでやくごみりをめやすとする。","en":"Chain sag ~5mm at tip is a check.","reason":"Manufacturer-specific but common check.","source":"gaikoku-11 p.21","answer":true},
  {"jp":"フルグリップを保ち、人差し指を外さない。","hira":"ふるぐりっぷをたもち、ひとさしゆびをはずさない。","en":"Keep full wrap grip; do not compromise grip.","reason":"Kickback control.","source":"gaikoku-11 p.20","answer":true},
  {"jp":"体の正中線上で切るのが安全である。","hira":"からだのせいちゅうせんじょうできるのがあんぜんである。","en":"Cut in line with your body.","reason":"False — offset stance safer.","source":"gaikoku-11 p.20","answer":false},
  {"jp":"落下先に人や道路がないことを確認する。","hira":"らっかさきにひとやどうろがないことをかくにんする。","en":"Ensure no people/roads in landing area.","reason":"Public safety.","source":"gaikoku-11 p.12","answer":true},
  {"jp":"腰より高い枝打ちは無理をしない。","hira":"こしよりたかいえだうちはむりをしない。","en":"Avoid overreaching above waist.","reason":"Prevent injuries.","source":"gaikoku-11 p.18","answer":true},
  {"jp":"暑い日は防護服を着用しなくてよい。","hira":"あついひはぼうごふくをちゃくようしなくてよい。","en":"Skip PPE on hot days.","reason":"False — manage heat but keep PPE.","source":"gaikoku-11 p.22","answer":false},
  {"jp":"目立ては左右の長さを揃える。","hira":"めたてはさゆうのながさをそろえる。","en":"Equalize cutter lengths.","reason":"Avoid curved cutting.","source":"gaikoku-11 p.21","answer":true},
  {"jp":"バック時は合図者を付ける。","hira":"ばっくじはあいずしゃをつける。","en":"Use spotter when reversing.","reason":"Prevent collisions.","source":"ringyo p.12","answer":true},
  {"jp":"待避は最低3m、状況でより広く取る。","hira":"たいひはさいていさんめーとる、じょうきょうでよりひろくとる。","en":"Retreat at least 3m; more if needed.","reason":"Adjust to hazards.","source":"gaikoku-11 p.15","answer":true},
  {"jp":"受口なしで倒すのが最も効率的である。","hira":"うけぐちなしでたおすのがもっともこうりつてきである。","en":"Felling without a notch is best.","reason":"False — notch controls direction.","source":"gaikoku-11 p.12","answer":false}
];

export default questions;
